name: runpythoncode

on: [push, pull_request]
 
jobs:
  demo1:
    runs-on: ubuntu-latest
    container:
      image: openjdk:24-slim-bullseye
    steps:
    - uses: actions/checkout@v4
    - name: compile
      run: |
        javac Hello.java
    - name: run code
      run: java Hello
    
